onnx_path: "policy.onnx"
pt_path: "policy.pt"
motion_file: "50fps_fightAndSports1_subject1.csv"
fps: 50

kp_lab: [40.20, 40.20, 40.20, 99.10, 99.10, 28.50,
         40.20, 40.20, 28.50, 99.10, 99.10, 14.30,
         14.30, 28.50, 28.50, 14.30, 14.30, 28.50,
         28.50, 14.30, 14.30, 14.30, 14.30, 14.30,
         14.30, 16.80, 16.80, 16.80, 16.80]

kd_lab: [2.56, 2.56, 2.56, 6.31, 6.31, 1.81,
         2.56, 2.56, 1.81, 6.31, 6.31, 0.91,
         0.91, 1.81, 1.81, 0.91, 0.91, 1.81,
         1.81, 0.91, 0.91, 0.91, 0.91, 0.91,
         0.91, 1.07, 1.07, 1.07, 1.07]

default_angles_lab: [-0.312, -0.312, 0.0, 0.0, 0.0, 0.0,
                     0.0, 0.0, 0.0, 0.669, 0.669, 0.2,
                     0.2, -0.363, -0.363, 0.2, -0.2, 0.0,
                     0.0, 0.0, 0.0, 0.6, 0.6, 0.0,
                     0.0, 0.0, 0.0, 0.0, 0.0]

action_scale_lab: [0.548, 0.548, 0.548, 0.351, 0.351, 0.439,
                   0.548, 0.548, 0.439, 0.351, 0.351, 0.439,
                   0.439, 0.439, 0.439, 0.439, 0.439, 0.439,
                   0.439, 0.439, 0.439, 0.439, 0.439, 0.439,
                   0.439, 0.075, 0.075, 0.075, 0.075]

num_actions: 29
num_obs: 154

mj2lab: [0, 6, 12,
         1, 7, 13,
         2, 8, 14,
         3, 9, 15, 22,
         4, 10, 16, 23,
         5, 11, 17, 24,
         18, 25,
         19, 26,
         20, 27,
         21, 28]
