onnx_path: "policy.onnx"
pt_path: "policy.pt"
motion_file: "50fps_dance1_subject2.csv"
fps: 50

tau_limit: [88.0, 88.0, 88.0,
            88.0, 88.0, 88.0,
            88.0, 88.0, 88.0,
            139.0, 139.0, 25.0, 25.0,
            50.0, 50.0, 25.0, 25.0,
            50.0, 50.0, 25.0, 25.0,
            25.0, 25.0,
            5.0, 5.0,
            5.0, 5.0,
            5.0, 5.0]

kp_lab: [40.179, 40.179, 40.179, 99.098, 99.098, 28.501,
         40.179, 40.179, 28.501, 99.098, 99.098, 14.251,
         14.251, 28.501, 28.501, 14.251, 14.251, 28.501,
         28.501, 14.251, 14.251, 14.251, 14.251, 14.251,
         14.251, 16.778, 16.778, 16.778, 16.778]

kd_lab: [2.558, 2.558, 2.558, 6.309, 6.309, 1.814,
         2.558, 2.558, 1.814, 6.309, 6.309, 0.907,
         0.907, 1.814, 1.814, 0.907, 0.907, 1.814,
         1.814, 0.907, 0.907, 0.907, 0.907, 0.907,
         0.907, 1.068, 1.068, 1.068, 1.068]

default_angles_lab: [-0.312, -0.312, 0.0, 0.0, 0.0, 0.0,
                     0.0, 0.0, 0.0, 0.669, 0.669, 0.2,
                     0.2, -0.363, -0.363, 0.2, -0.2, 0.0,
                     0.0, 0.0, 0.0, 0.6, 0.6, 0.0,
                     0.0, 0.0, 0.0, 0.0, 0.0]

action_scale_lab: [0.548, 0.548, 0.548, 0.351, 0.351, 0.439,
                   0.548, 0.548, 0.439, 0.351, 0.351, 0.439,
                   0.439, 0.439, 0.439, 0.439, 0.439, 0.439,
                   0.439, 0.439, 0.439, 0.439, 0.439, 0.439,
                   0.439, 0.075, 0.075, 0.075, 0.075]

num_actions: 29
num_obs: 154

mj2lab: [0, 6, 12,
         1, 7, 13,
         2, 8, 14,
         3, 9, 15, 22,
         4, 10, 16, 23,
         5, 11, 17, 24,
         18, 25,
         19, 26,
         20, 27,
         21, 28]
